name: rick_and_morty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_localization: ^0.1.13

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logoRick.png"
  adaptive_icon_background: "#11211f"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/img/real_logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/img/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  background_image: assets/img/start_screen_logo.png

